In [2]:
import numpy as np


a = np.arange(9).reshape(3,3)
names = []
name = "m"
for x in range(0,a.shape[0]):
    for y in range(0,a.shape[1]):
        names.append(f"{name}{x}{y}")

print(names)
print(a.flatten().tolist())


['m00', 'm01', 'm02', 'm10', 'm11', 'm12', 'm20', 'm21', 'm22']
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [24]:
K = np.array([
            [ 1.1, 2.1, 3.1],
            [ 1.2, 2.2, 3.2],
            [ 1.3, 2.3, 3.3]
        ], dtype=np.float32)
print(K[:,[0,1]])
print(K[:,[2]])

t=np.array([4.1, 4.2, 4.3],dtype=np.float32)
H=np.column_stack([K[:,[0,1]], t])
print("???")
print(H @ K)








[[1.1 2.1]
 [1.2 2.2]
 [1.3 2.3]]
[[3.1]
 [3.2]
 [3.3]]
???
[[ 9.059999 16.359999 23.66    ]
 [ 9.42     17.019999 24.619999]
 [ 9.78     17.68     25.58    ]]
